version: "3.1"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: Reactivities
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user